"""Initial schema with scenario C.

Bootstraps:
- PostgreSQL extensions (postgis, postgis_topology, pg_trgm, unaccent, uuid-ossp)
- 9 ENUM types
- 17 tables (Scenarios A/B + C + analysis cache)
- All B-tree, GIN, and GIST indexes
- 3 views (v_project_nearby_transactions, v_road_yearly_metrics, v_store_full_profile)

This file is hand-written rather than autogenerated so the extension/view
ordering is explicit. Subsequent migrations should be ``alembic revision
--autogenerate -m "..."``.

Revision ID: 20260507_0001
Revises:
Create Date: 2026-05-07
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from geoalchemy2 import Geometry
from sqlalchemy.dialects import postgresql

# Revision identifiers, used by Alembic.
revision: str = "20260507_0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


# ─── ENUM definitions (single source of truth in this migration) ────────────


def _enum(name: str, *values: str) -> postgresql.ENUM:
    return postgresql.ENUM(*values, name=name, create_type=False)


PROJECT_TYPE = ("public_housing", "urban_development", "industrial_complex",
                "logistics", "new_town", "other")
PROJECT_STAGE_KIND = (
    "planned", "announced", "designated", "compensation_planned",
    "compensation_started", "relocation_complete", "ground_break",
    "under_construction", "completion",
)
ADMIN_LEVEL = ("sido", "sigungu", "eupmyeondong")
TRANSACTION_TYPE = ("land", "apartment", "officetel", "single_house", "commercial", "other")
ROAD_STAGE_KIND = ("planned", "design", "under_construction", "completed")
STORE_TYPE = ("DT", "DI", "standard", "kiosk")
BRAND_CATEGORY = ("cafe", "fastfood", "bakery", "convenience", "other")
ANALYSIS_SCENARIO = ("a", "b", "c")
ANALYSIS_STATUS = ("queued", "running", "completed", "failed")


def upgrade() -> None:
    # ─── Extensions ─────────────────────────────────────────────────────
    op.execute("CREATE EXTENSION IF NOT EXISTS postgis")
    op.execute("CREATE EXTENSION IF NOT EXISTS postgis_topology")
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    op.execute("CREATE EXTENSION IF NOT EXISTS unaccent")
    op.execute('CREATE EXTENSION IF NOT EXISTS "uuid-ossp"')

    # ─── ENUMs ──────────────────────────────────────────────────────────
    bind = op.get_bind()
    for name, values in [
        ("project_type", PROJECT_TYPE),
        ("project_stage_kind", PROJECT_STAGE_KIND),
        ("admin_level", ADMIN_LEVEL),
        ("transaction_type", TRANSACTION_TYPE),
        ("road_stage_kind", ROAD_STAGE_KIND),
        ("store_type", STORE_TYPE),
        ("brand_category", BRAND_CATEGORY),
        ("analysis_scenario", ANALYSIS_SCENARIO),
        ("analysis_status", ANALYSIS_STATUS),
    ]:
        postgresql.ENUM(*values, name=name).create(bind, checkfirst=True)

    # ─── admin_areas (referenced by many tables) ────────────────────────
    op.create_table(
        "admin_areas",
        sa.Column("code", sa.String(10), primary_key=True),
        sa.Column("name", sa.String(100), nullable=False),
        sa.Column("level", _enum("admin_level", *ADMIN_LEVEL), nullable=False),
        sa.Column("parent_code", sa.String(10),
                  sa.ForeignKey("admin_areas.code", ondelete="SET NULL"),
                  nullable=True),
        sa.Column("geometry", Geometry("MULTIPOLYGON", srid=4326,
                                        spatial_index=False), nullable=True),
        sa.Column("centroid", Geometry("POINT", srid=4326,
                                        spatial_index=False), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True),
                  server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True),
                  server_default=sa.func.now(), nullable=False),
    )
    op.create_index("ix_admin_areas_level", "admin_areas", ["level"])
    op.execute(
        "CREATE INDEX ix_admin_areas_name_trgm ON admin_areas "
        "USING gin (name gin_trgm_ops)"
    )
    op.execute(
        "CREATE INDEX gix_admin_areas_geometry ON admin_areas USING gist (geometry)"
    )
    op.execute(
        "CREATE INDEX gix_admin_areas_centroid ON admin_areas USING gist (centroid)"
    )

    # ─── projects ───────────────────────────────────────────────────────
    op.create_table(
        "projects",
        sa.Column("id", sa.BigInteger, primary_key=True, autoincrement=True),
        sa.Column("name", sa.String(200), nullable=False),
        sa.Column("project_type", _enum("project_type", *PROJECT_TYPE),
                  nullable=False),
        sa.Column("region_code", sa.String(10),
                  sa.ForeignKey("admin_areas.code", ondelete="SET NULL")),
        sa.Column("geometry", Geometry("MULTIPOLYGON", srid=4326,
                                        spatial_index=False), nullable=True),
        sa.Column("centroid", Geometry("POINT", srid=4326,
                                        spatial_index=False), nullable=True),
        sa.Column("area_ha", sa.Numeric(10, 2), nullable=True),
        sa.Column("expected_compensation_billion_krw", sa.Numeric(12, 2),
                  nullable=True),
        sa.Column("planned_announcement_date", sa.Date, nullable=True),
        sa.Column("planned_completion_date", sa.Date, nullable=True),
        sa.Column("description", sa.Text, nullable=True),
        sa.Column("source", sa.String(200), nullable=True),
        sa.Column("raw_data", postgresql.JSONB, nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True),
                  server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True),
                  server_default=sa.func.now(), nullable=False),
        sa.UniqueConstraint("name", "project_type", name="uq_projects_name_type"),
    )
    op.create_index("ix_projects_region_code", "projects", ["region_code"])
    op.create_index("ix_projects_type", "projects", ["project_type"])
    op.execute("CREATE INDEX gix_projects_geometry ON projects USING gist (geometry)")
    op.execute("CREATE INDEX gix_projects_centroid ON projects USING gist (centroid)")

    # ─── project_stages ─────────────────────────────────────────────────
    op.create_table(
        "project_stages",
        sa.Column("id", sa.BigInteger, primary_key=True, autoincrement=True),
        sa.Column("project_id", sa.BigInteger,
                  sa.ForeignKey("projects.id", ondelete="CASCADE"),
                  nullable=False),
        sa.Column("stage", _enum("project_stage_kind", *PROJECT_STAGE_KIND),
                  nullable=False),
        sa.Column("occurred_at", sa.Date, nullable=False),
        sa.Column("sequence_no", sa.Integer, nullable=True),
        sa.Column("note", sa.Text, nullable=True),
        sa.Column("source", sa.String(200), nullable=True),
        sa.Column("raw_data", postgresql.JSONB, nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True),
                  server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True),
                  server_default=sa.func.now(), nullable=False),
        sa.UniqueConstraint("project_id", "stage", "occurred_at",
                            name="uq_project_stages_project_stage_date"),
    )
    op.create_index("ix_project_stages_project_id", "project_stages", ["project_id"])
    op.create_index("ix_project_stages_occurred_at", "project_stages", ["occurred_at"])

    # ─── land_transactions ──────────────────────────────────────────────
    op.create_table(
        "land_transactions",
        sa.Column("id", sa.BigInteger, primary_key=True, autoincrement=True),
        sa.Column("source_id", sa.String(64), nullable=False, unique=True),
        sa.Column("source", sa.String(50), nullable=False, server_default="molit"),
        sa.Column("region_code", sa.String(10),
                  sa.ForeignKey("admin_areas.code", ondelete="SET NULL")),
        sa.Column("pnu", sa.String(19), nullable=True),
        sa.Column("address", sa.String(255), nullable=True),
        sa.Column("location", Geometry("POINT", srid=4326, spatial_index=False),
                  nullable=True),
        sa.Column("transaction_type", _enum("transaction_type", *TRANSACTION_TYPE),
                  nullable=False),
        sa.Column("contract_date", sa.Date, nullable=False),
        sa.Column("deal_amount_krw", sa.BigInteger, nullable=False),
        sa.Column("area_m2", sa.Numeric(12, 2), nullable=True),
        sa.Column("floor", sa.Integer, nullable=True),
        sa.Column("use_district", sa.String(50), nullable=True),
        sa.Column("raw_data", postgresql.JSONB, nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True),
                  server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True),
                  server_default=sa.func.now(), nullable=False),
    )
    op.create_index("ix_land_transactions_region_date", "land_transactions",
                    ["region_code", "contract_date"])
    op.create_index("ix_land_transactions_pnu", "land_transactions", ["pnu"])
    op.create_index("ix_land_transactions_type_date", "land_transactions",
                    ["transaction_type", "contract_date"])
    op.execute(
        "CREATE INDEX gix_land_transactions_location "
        "ON land_transactions USING gist (location)"
    )

    # ─── road_segments ──────────────────────────────────────────────────
    op.create_table(
        "road_segments",
        sa.Column("id", sa.BigInteger, primary_key=True, autoincrement=True),
        sa.Column("name", sa.String(200), nullable=False),
        sa.Column("route_no", sa.String(50), nullable=True),
        sa.Column("region_code", sa.String(10),
                  sa.ForeignKey("admin_areas.code", ondelete="SET NULL")),
        sa.Column("geometry", Geometry("LINESTRING", srid=4326,
                                        spatial_index=False), nullable=True),
        sa.Column("length_m", sa.Numeric(10, 2), nullable=True),
        sa.Column("description", sa.Text, nullable=True),
        sa.Column("source", sa.String(200), nullable=True),
        sa.Column("raw_data", postgresql.JSONB, nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True),
                  server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True),
                  server_default=sa.func.now(), nullable=False),
        sa.UniqueConstraint("name", "route_no", name="uq_road_segments_name_route"),
    )
    op.create_index("ix_road_segments_region_code", "road_segments", ["region_code"])
    op.execute(
        "CREATE INDEX gix_road_segments_geometry "
        "ON road_segments USING gist (geometry)"
    )

    # ─── road_expansion_stages ──────────────────────────────────────────
    op.create_table(
        "road_expansion_stages",
        sa.Column("id", sa.BigInteger, primary_key=True, autoincrement=True),
        sa.Column("road_id", sa.BigInteger,
                  sa.ForeignKey("road_segments.id", ondelete="CASCADE"),
                  nullable=False),
        sa.Column("stage", _enum("road_stage_kind", *ROAD_STAGE_KIND),
                  nullable=False),
        sa.Column("occurred_at", sa.Date, nullable=False),
        sa.Column("lanes_before", sa.Integer, nullable=True),
        sa.Column("lanes_after", sa.Integer, nullable=True),
        sa.Column("width_before_m", sa.Numeric(6, 2), nullable=True),
        sa.Column("width_after_m", sa.Numeric(6, 2), nullable=True),
        sa.Column("note", sa.Text, nullable=True),
        sa.Column("source", sa.String(200), nullable=True),
        sa.Column("raw_data", postgresql.JSONB, nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True),
                  server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True),
                  server_default=sa.func.now(), nullable=False),
        sa.UniqueConstraint("road_id", "stage", "occurred_at",
                            name="uq_road_expansion_stages_road_stage_date"),
    )
    op.create_index("ix_road_expansion_stages_road_id",
                    "road_expansion_stages", ["road_id"])
    op.create_index("ix_road_expansion_stages_occurred_at",
                    "road_expansion_stages", ["occurred_at"])

    # ─── traffic_volumes ────────────────────────────────────────────────
    op.create_table(
        "traffic_volumes",
        sa.Column("id", sa.BigInteger, primary_key=True, autoincrement=True),
        sa.Column("road_id", sa.BigInteger,
                  sa.ForeignKey("road_segments.id", ondelete="CASCADE"),
                  nullable=False),
        sa.Column("observed_at", sa.Date, nullable=False),
        sa.Column("aadt", sa.Integer, nullable=False),
        sa.Column("peak_hour_volume", sa.Integer, nullable=True),
        sa.Column("heavy_vehicle_pct", sa.Numeric(5, 2), nullable=True),
        sa.Column("source", sa.String(200), nullable=True),
        sa.Column("raw_data", postgresql.JSONB, nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True),
                  server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True),
                  server_default=sa.func.now(), nullable=False),
        sa.UniqueConstraint("road_id", "observed_at",
                            name="uq_traffic_volumes_road_observed_at"),
    )
    op.create_index("ix_traffic_volumes_observed_at",
                    "traffic_volumes", ["observed_at"])

    # ─── population_stats ───────────────────────────────────────────────
    op.create_table(
        "population_stats",
        sa.Column("id", sa.BigInteger, primary_key=True, autoincrement=True),
        sa.Column("region_code", sa.String(10),
                  sa.ForeignKey("admin_areas.code", ondelete="CASCADE"),
                  nullable=False),
        sa.Column("observed_at", sa.Date, nullable=False),
        sa.Column("total_population", sa.Integer, nullable=False),
        sa.Column("male_population", sa.Integer, nullable=True),
        sa.Column("female_population", sa.Integer, nullable=True),
        sa.Column("household_count", sa.Integer, nullable=True),
        sa.Column("avg_age", sa.Numeric(5, 2), nullable=True),
        sa.Column("source", sa.String(200), nullable=True),
        sa.Column("raw_data", postgresql.JSONB, nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True),
                  server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True),
                  server_default=sa.func.now(), nullable=False),
        sa.UniqueConstraint("region_code", "observed_at",
                            name="uq_population_stats_region_observed_at"),
    )
    op.create_index("ix_population_stats_observed_at",
                    "population_stats", ["observed_at"])

    # ─── buildings (Scenario C) ─────────────────────────────────────────
    op.create_table(
        "buildings",
        sa.Column("pnu", sa.String(19), primary_key=True),
        sa.Column("address", sa.String(255), nullable=True),
        sa.Column("region_code", sa.String(10),
                  sa.ForeignKey("admin_areas.code", ondelete="SET NULL")),
        sa.Column("parcel_area_m2", sa.Numeric(12, 2), nullable=True),
        sa.Column("building_area_m2", sa.Numeric(12, 2), nullable=True),
        sa.Column("total_floor_area_m2", sa.Numeric(12, 2), nullable=True),
        sa.Column("floors_above", sa.Integer, nullable=True),
        sa.Column("floors_below", sa.Integer, nullable=True),
        sa.Column("use_type", sa.String(100), nullable=True),
        sa.Column("structure", sa.String(100), nullable=True),
        sa.Column("approval_date", sa.Date, nullable=True),
        sa.Column("geometry", Geometry("POLYGON", srid=4326,
                                        spatial_index=False), nullable=True),
        sa.Column("description", sa.Text, nullable=True),
        sa.Column("source", sa.String(200), nullable=True),
        sa.Column("raw_data", postgresql.JSONB, nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True),
                  server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True),
                  server_default=sa.func.now(), nullable=False),
    )
    op.create_index("ix_buildings_region_code", "buildings", ["region_code"])
    op.create_index("ix_buildings_use_type", "buildings", ["use_type"])
    op.create_index("ix_buildings_approval_date", "buildings", ["approval_date"])
    op.execute(
        "CREATE INDEX gix_buildings_geometry ON buildings USING gist (geometry)"
    )

    # ─── store_brands ───────────────────────────────────────────────────
    op.create_table(
        "store_brands",
        sa.Column("id", sa.BigInteger, primary_key=True, autoincrement=True),
        sa.Column("name", sa.String(100), nullable=False),
        sa.Column("name_en", sa.String(100), nullable=True),
        sa.Column("category", _enum("brand_category", *BRAND_CATEGORY),
                  nullable=False),
        sa.Column("country", sa.String(10), nullable=True),
        sa.Column("homepage", sa.String(255), nullable=True),
        sa.Column("description", sa.Text, nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True),
                  server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True),
                  server_default=sa.func.now(), nullable=False),
        sa.UniqueConstraint("name", name="uq_store_brands_name"),
    )
    op.create_index("ix_store_brands_category", "store_brands", ["category"])

    # ─── stores ─────────────────────────────────────────────────────────
    op.create_table(
        "stores",
        sa.Column("id", sa.BigInteger, primary_key=True, autoincrement=True),
        sa.Column("brand_id", sa.BigInteger,
                  sa.ForeignKey("store_brands.id", ondelete="RESTRICT"),
                  nullable=False),
        sa.Column("source_id", sa.String(100), nullable=True),
        sa.Column("source_url", sa.String(500), nullable=True),
        sa.Column("name", sa.String(200), nullable=False),
        sa.Column("address", sa.String(255), nullable=True),
        sa.Column("region_code", sa.String(10),
                  sa.ForeignKey("admin_areas.code", ondelete="SET NULL")),
        sa.Column("location", Geometry("POINT", srid=4326, spatial_index=False),
                  nullable=True),
        sa.Column("pnu", sa.String(19),
                  sa.ForeignKey("buildings.pnu", ondelete="SET NULL"),
                  nullable=True),
        sa.Column("store_type", _enum("store_type", *STORE_TYPE), nullable=False),
        sa.Column("purchase_date", sa.Date, nullable=True),
        sa.Column("construction_approval_date", sa.Date, nullable=True),
        sa.Column("opened_at", sa.Date, nullable=True),
        sa.Column("closed_at", sa.Date, nullable=True),
        sa.Column("land_area_m2", sa.Numeric(12, 2), nullable=True),
        sa.Column("building_area_m2", sa.Numeric(12, 2), nullable=True),
        sa.Column("note", sa.Text, nullable=True),
        sa.Column("raw_data", postgresql.JSONB, nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True),
                  server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True),
                  server_default=sa.func.now(), nullable=False),
        sa.UniqueConstraint("brand_id", "source_id",
                            name="uq_stores_brand_source_id"),
    )
    op.create_index("ix_stores_brand_id", "stores", ["brand_id"])
    op.create_index("ix_stores_pnu", "stores", ["pnu"])
    op.create_index("ix_stores_region_code", "stores", ["region_code"])
    op.create_index("ix_stores_store_type", "stores", ["store_type"])
    op.create_index("ix_stores_opened_at", "stores", ["opened_at"])
    op.execute("CREATE INDEX gix_stores_location ON stores USING gist (location)")

    # ─── official_land_prices ───────────────────────────────────────────
    op.create_table(
        "official_land_prices",
        sa.Column("id", sa.BigInteger, primary_key=True, autoincrement=True),
        sa.Column("pnu", sa.String(19),
                  sa.ForeignKey("buildings.pnu", ondelete="CASCADE"),
                  nullable=False),
        sa.Column("year", sa.Integer, nullable=False),
        sa.Column("price_per_m2", sa.BigInteger, nullable=False),
        sa.Column("change_rate", sa.Numeric(7, 4), nullable=True),
        sa.Column("source", sa.String(200), nullable=True),
        sa.Column("raw_data", postgresql.JSONB, nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True),
                  server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True),
                  server_default=sa.func.now(), nullable=False),
        sa.UniqueConstraint("pnu", "year", name="uq_official_land_prices_pnu_year"),
    )
    op.create_index("ix_official_land_prices_year",
                    "official_land_prices", ["year"])

    # ─── store_features ─────────────────────────────────────────────────
    op.create_table(
        "store_features",
        sa.Column("id", sa.BigInteger, primary_key=True, autoincrement=True),
        sa.Column("store_id", sa.BigInteger,
                  sa.ForeignKey("stores.id", ondelete="CASCADE"),
                  nullable=False),
        sa.Column("snapshot_date", sa.Date, nullable=False),
        sa.Column("version", sa.String(20), nullable=False, server_default="v1"),
        sa.Column("population_within_1km", sa.Integer, nullable=True),
        sa.Column("population_within_3km", sa.Integer, nullable=True),
        sa.Column("aadt_nearest_road", sa.Integer, nullable=True),
        sa.Column("distance_to_nearest_road_m", sa.Numeric(10, 2), nullable=True),
        sa.Column("competitor_count_within_1km", sa.Integer, nullable=True),
        sa.Column("land_price_per_m2", sa.BigInteger, nullable=True),
        sa.Column("feature_vector", postgresql.JSONB, nullable=False,
                  server_default=sa.text("'{}'::jsonb")),
        sa.Column("created_at", sa.DateTime(timezone=True),
                  server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True),
                  server_default=sa.func.now(), nullable=False),
        sa.UniqueConstraint("store_id", "snapshot_date", "version",
                            name="uq_store_features_store_date_version"),
    )
    op.create_index("ix_store_features_snapshot_date",
                    "store_features", ["snapshot_date"])

    # ─── candidate_lands ────────────────────────────────────────────────
    op.create_table(
        "candidate_lands",
        sa.Column("id", sa.BigInteger, primary_key=True, autoincrement=True),
        sa.Column("pnu", sa.String(19),
                  sa.ForeignKey("buildings.pnu", ondelete="CASCADE"),
                  nullable=False),
        sa.Column("address", sa.String(255), nullable=True),
        sa.Column("location", Geometry("POINT", srid=4326, spatial_index=False),
                  nullable=True),
        sa.Column("suitability_score", sa.Numeric(7, 4), nullable=False),
        sa.Column("breakdown", postgresql.JSONB, nullable=False,
                  server_default=sa.text("'{}'::jsonb")),
        sa.Column("model_name", sa.String(100), nullable=False),
        sa.Column("model_version", sa.String(20), nullable=False),
        sa.Column("evaluated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("note", sa.Text, nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True),
                  server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True),
                  server_default=sa.func.now(), nullable=False),
        sa.UniqueConstraint(
            "pnu", "model_name", "model_version", "evaluated_at",
            name="uq_candidate_lands_pnu_model_version_evaluated",
        ),
    )
    op.create_index("ix_candidate_lands_pnu", "candidate_lands", ["pnu"])
    op.create_index("ix_candidate_lands_score", "candidate_lands",
                    ["suitability_score"])
    op.execute(
        "CREATE INDEX gix_candidate_lands_location "
        "ON candidate_lands USING gist (location)"
    )

    # ─── store_impact_analysis ──────────────────────────────────────────
    op.create_table(
        "store_impact_analysis",
        sa.Column("id", sa.BigInteger, primary_key=True, autoincrement=True),
        sa.Column("store_id", sa.BigInteger,
                  sa.ForeignKey("stores.id", ondelete="CASCADE"),
                  nullable=False),
        sa.Column("distance_band_m", sa.Integer, nullable=False),
        sa.Column("pre_window_start", sa.Date, nullable=False),
        sa.Column("pre_window_end", sa.Date, nullable=False),
        sa.Column("post_window_start", sa.Date, nullable=False),
        sa.Column("post_window_end", sa.Date, nullable=False),
        sa.Column("pre_open_avg_price_per_m2", sa.BigInteger, nullable=True),
        sa.Column("post_open_avg_price_per_m2", sa.BigInteger, nullable=True),
        sa.Column("change_rate", sa.Numeric(7, 4), nullable=True),
        sa.Column("pre_sample_size", sa.Integer, nullable=False, server_default="0"),
        sa.Column("post_sample_size", sa.Integer, nullable=False, server_default="0"),
        sa.Column("method", sa.String(50), nullable=True),
        sa.Column("extra", postgresql.JSONB, nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True),
                  server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True),
                  server_default=sa.func.now(), nullable=False),
        sa.UniqueConstraint(
            "store_id", "distance_band_m", "post_window_end",
            name="uq_store_impact_store_band_window",
        ),
    )
    op.create_index("ix_store_impact_store_id",
                    "store_impact_analysis", ["store_id"])
    op.create_index("ix_store_impact_distance_band",
                    "store_impact_analysis", ["distance_band_m"])

    # ─── analysis_results ───────────────────────────────────────────────
    op.create_table(
        "analysis_results",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True,
                  server_default=sa.text("uuid_generate_v4()")),
        sa.Column("scenario", _enum("analysis_scenario", *ANALYSIS_SCENARIO),
                  nullable=False),
        sa.Column("entity_type", sa.String(50), nullable=False),
        sa.Column("entity_id", sa.String(100), nullable=False),
        sa.Column("params_hash", sa.String(64), nullable=False),
        sa.Column("status", _enum("analysis_status", *ANALYSIS_STATUS),
                  nullable=False, server_default="completed"),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("params", postgresql.JSONB, nullable=False,
                  server_default=sa.text("'{}'::jsonb")),
        sa.Column("result", postgresql.JSONB, nullable=True),
        sa.Column("error", sa.Text, nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True),
                  server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True),
                  server_default=sa.func.now(), nullable=False),
        sa.UniqueConstraint(
            "scenario", "entity_type", "entity_id", "params_hash",
            name="uq_analysis_results_scenario_entity_params",
        ),
    )
    op.create_index("ix_analysis_results_status", "analysis_results", ["status"])
    op.create_index("ix_analysis_results_expires_at",
                    "analysis_results", ["expires_at"])

    # ─── recommendations ────────────────────────────────────────────────
    op.create_table(
        "recommendations",
        sa.Column("id", sa.BigInteger, primary_key=True, autoincrement=True),
        sa.Column("source_entity_type", sa.String(50), nullable=False),
        sa.Column("source_entity_id", sa.String(100), nullable=False),
        sa.Column("target_entity_type", sa.String(50), nullable=False),
        sa.Column("target_entity_id", sa.String(100), nullable=False),
        sa.Column("score", sa.Numeric(7, 4), nullable=False),
        sa.Column("rank", sa.Integer, nullable=False),
        sa.Column("model_version", sa.String(20), nullable=False),
        sa.Column("extra", postgresql.JSONB, nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True),
                  server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True),
                  server_default=sa.func.now(), nullable=False),
        sa.UniqueConstraint(
            "source_entity_type", "source_entity_id",
            "target_entity_type", "target_entity_id",
            "model_version",
            name="uq_recommendations_source_target_version",
        ),
    )
    op.create_index(
        "ix_recommendations_source", "recommendations",
        ["source_entity_type", "source_entity_id", "rank"],
    )

    # ─── Views ──────────────────────────────────────────────────────────
    # 1. Project × nearby transactions (for Scenario A regression input).
    op.execute("""
        CREATE OR REPLACE VIEW v_project_nearby_transactions AS
        SELECT
            p.id            AS project_id,
            p.name          AS project_name,
            p.project_type  AS project_type,
            t.id            AS transaction_id,
            t.contract_date AS contract_date,
            t.deal_amount_krw,
            t.area_m2,
            t.transaction_type,
            t.location      AS transaction_location,
            ST_Distance(
                p.geometry::geography,
                t.location::geography
            ) AS distance_m
        FROM projects p
        JOIN land_transactions t
          ON p.geometry IS NOT NULL
         AND t.location IS NOT NULL
         AND ST_DWithin(
             p.geometry::geography,
             t.location::geography,
             5000  -- 5km halo
         );
    """)

    # 2. Road yearly metrics (Scenario B time-series rollup).
    op.execute("""
        CREATE OR REPLACE VIEW v_road_yearly_metrics AS
        WITH yearly_traffic AS (
            SELECT
                road_id,
                date_trunc('year', observed_at)::date AS year_start,
                AVG(aadt)::int                         AS avg_aadt,
                MAX(peak_hour_volume)                  AS peak_volume,
                COUNT(*)                               AS sample_size
            FROM traffic_volumes
            GROUP BY road_id, date_trunc('year', observed_at)
        ),
        yearly_population AS (
            SELECT
                rs.id                                  AS road_id,
                date_trunc('year', ps.observed_at)::date AS year_start,
                AVG(ps.total_population)::int           AS avg_population,
                AVG(ps.household_count)::int            AS avg_households
            FROM road_segments rs
            JOIN population_stats ps
              ON ps.region_code = rs.region_code
            GROUP BY rs.id, date_trunc('year', ps.observed_at)
        )
        SELECT
            COALESCE(t.road_id, p.road_id)          AS road_id,
            COALESCE(t.year_start, p.year_start)    AS year_start,
            t.avg_aadt,
            t.peak_volume,
            p.avg_population,
            p.avg_households
        FROM yearly_traffic t
        FULL OUTER JOIN yearly_population p
          ON t.road_id = p.road_id
         AND t.year_start = p.year_start;
    """)

    # 3. Store full profile (Scenario C training table view).
    op.execute("""
        CREATE OR REPLACE VIEW v_store_full_profile AS
        WITH price_series AS (
            SELECT
                pnu,
                jsonb_object_agg(year::text, price_per_m2 ORDER BY year) AS price_by_year,
                MAX(year)                                                AS latest_year,
                MIN(year)                                                AS first_year,
                MAX(price_per_m2) FILTER (WHERE year = (
                    SELECT MAX(year) FROM official_land_prices ip WHERE ip.pnu = olp.pnu
                ))                                                        AS latest_price,
                MAX(price_per_m2) FILTER (WHERE year = (
                    SELECT MIN(year) FROM official_land_prices ip WHERE ip.pnu = olp.pnu
                ))                                                        AS earliest_price
            FROM official_land_prices olp
            GROUP BY pnu
        )
        SELECT
            s.id                              AS store_id,
            s.name                            AS store_name,
            s.store_type,
            sb.name                           AS brand_name,
            sb.category                       AS brand_category,
            s.address,
            s.location,
            s.pnu,
            s.opened_at,
            s.land_area_m2,
            s.building_area_m2,
            b.use_type,
            b.approval_date,
            b.total_floor_area_m2,
            ps.price_by_year,
            ps.first_year,
            ps.latest_year,
            ps.earliest_price,
            ps.latest_price,
            CASE
                WHEN ps.earliest_price IS NULL OR ps.earliest_price = 0 THEN NULL
                ELSE ROUND(
                    ((ps.latest_price::numeric / ps.earliest_price::numeric) - 1) * 100,
                    2
                )
            END AS price_change_pct
        FROM stores s
        JOIN store_brands sb ON sb.id = s.brand_id
        LEFT JOIN buildings b ON b.pnu = s.pnu
        LEFT JOIN price_series ps ON ps.pnu = s.pnu;
    """)


def downgrade() -> None:
    # Drop views first, then tables (in reverse FK order), then ENUMs/extensions.
    for view in (
        "v_store_full_profile",
        "v_road_yearly_metrics",
        "v_project_nearby_transactions",
    ):
        op.execute(f"DROP VIEW IF EXISTS {view}")

    for table in (
        "recommendations",
        "analysis_results",
        "store_impact_analysis",
        "candidate_lands",
        "store_features",
        "official_land_prices",
        "stores",
        "store_brands",
        "buildings",
        "population_stats",
        "traffic_volumes",
        "road_expansion_stages",
        "road_segments",
        "land_transactions",
        "project_stages",
        "projects",
        "admin_areas",
    ):
        op.drop_table(table)

    bind = op.get_bind()
    for name in (
        "analysis_status",
        "analysis_scenario",
        "brand_category",
        "store_type",
        "road_stage_kind",
        "transaction_type",
        "admin_level",
        "project_stage_kind",
        "project_type",
    ):
        postgresql.ENUM(name=name).drop(bind, checkfirst=True)
